apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-service-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # InitContainers block has been removed entirely.
      # The init script will now be mounted directly into the main MySQL container.
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb-volume # Volume mount for the init script ConfigMap
              mountPath: /docker-entrypoint-initdb.d/ # Mount to the special directory for MySQL init scripts
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes: # This is still under spec.template.spec.volumes
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-storage-mysql-0
        - name: mysql-initdb-volume # Volume definition for the init script ConfigMap
          configMap:
            name: mysql-initdb-script # Name of the ConfigMap created from src/init.sql
            # No 'items' field here, as we want to mount the whole ConfigMap as a directory.
            # The 'init.sql' file will appear directly under /docker-entrypoint-initdb.d/
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
