apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_DATABASE: ZXhhbXBsZURi
  MYSQL_USER: Zmxhc2thcHA=
  MYSQL_PASSWORD: Zmxhc2thcHA=