apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-service-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # This security context ensures the volume is owned by the mysql group
      securityContext:
        fsGroup: 999 
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            # Mount the persistent volume to the data directory
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            # Mount the init script from the ConfigMap to the correct init directory
            - name: mysql-initdb-volume
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        # Define the volume from the ConfigMap
        - name: mysql-initdb-volume
          configMap:
            name: mysql-initdb-script
  # Let the StatefulSet manage the Persistent Volume Claim creation
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard" # Explicitly use the default class for kind
        resources:
          requests:
            storage: 2Gi