apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=          # Base64 of 'rootpass' (סיסמת ROOT לבסיס הנתונים)
  MYSQL_DATABASE: ZXhhbXBsZURi              # Base64 of 'exampleDb' (שם בסיס הנתונים)
  MYSQL_USER: Zmxhc2thcHA=                  # Base64 of 'flaskapp' (שם המשתמש)
  MYSQL_PASSWORD: Zmxhc2thcHA=              # Base64 of 'flaskapp' (סיסמת המשתמש)