apiVersion: apps/v1
kind: Deployment
metadata:
  name: workprofile
spec:
  selector:
    matchLabels:
      app: workprofile
  replicas: 1
  template:
    metadata:
      labels:
        app: workprofile
    spec:
      containers:
        - name: workprofile
          image: YOUR_APP_IMAGE_PLACEHOLDER # זה יוחלף ב-CI/CD
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: workprofile-config # שימוש ב-ConfigMap עבור משתני סביבה
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 45 # הגדלתי את ההשהיה הראשונית
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5 # הגדלתי את מספר הניסיונות
