apiVersion: apps/v1
kind: Deployment
metadata:
  name: workprofile
spec:
  selector:
    matchLabels:
      app: workprofile
  replicas: 1
  template:
    metadata:
      labels:
        app: workprofile
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mysql-service-clusterip 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
        - name: workprofile
          image: YOUR_APP_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: workprofile-config
            - secretRef:
                name: mysql-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
