version: '3.8' 

services:
  nginx:
    image: nginx:latest 
    ports:
      - "8080:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    networks:
      - frontend_network 
      - backend_network 
    depends_on:
      - app 

  app:
    build:
      context: ../ 
      dockerfile: Dockerfile 
    ports:
      - "5000" 
    environment: 
      MYSQL_HOST: db 
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
      MYSQL_DB: workprofile_db 
    networks:
      - backend_network 
    depends_on:
      - db 

  db:
    image: mysql:8.0 
    environment: 
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: workprofile_db 
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
    volumes:
      - db_data:/var/lib/mysql 
      - ../src/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - backend_network 

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  db_data: 
