name: WorkProfile CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner | lower }}/${{ github.event.repository.name | lower }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get the latest tag from the repository and increment patch version
        id: increment_version
        run: |
          git fetch --tags
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            new_tag="1.0.0"
          else
            major=$(echo $latest_tag | cut -d '.' -f 1 | sed 's/v//')
            minor=$(echo $latest_tag | cut -d '.' -f 2)
            patch=$(echo $latest_tag | cut -d '.' -f 3)
            patch=$((patch + 1))
            new_tag="${major}.${minor}.${patch}"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build --load --tag $IMAGE_NAME:v${{ steps.increment_version.outputs.new_tag }} .

      - name: Run Docker container
        run: |
          docker run -d -p 8081:5000 --name workprofile-test-app $IMAGE_NAME:v${{ steps.increment_version.outputs.new_tag }}

      - name: Wait for app to be ready
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:8081/health | grep -q "Application: Healthy"; then
              echo "App is ready!"
              exit 0
            fi
            echo "Waiting for app to be ready..."
            sleep 2
          done
          echo "App did not become ready in time." && exit 1

      - name: Test root endpoint "/"
        run: |
          response_root=$(curl -s http://localhost:8081/)
          if echo "$response_root" | grep -q "DB Host:" && \
             echo "$response_root" | grep -q "Add Person" && \
             echo "$response_root" | grep -q "John Doe"; then
            echo "Root API test passed."
          else
            echo "Root API test FAILED. Response: $response_root"
            exit 1
          fi

      - name: Test health endpoint "/health"
        run: |
          response_health=$(curl -s http://localhost:8081/health)
          if echo "$response_health" | grep -q "Application: Healthy"; then
            echo "/health API test passed."
          else
            echo "/health API test FAILED. Response: $response_health"
            exit 1
          fi

      - name: Stop and remove container
        if: always()
        run: |
          docker rm -f workprofile-test-app || true

      - name: Push Git tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v' + '${{ steps.increment_version.outputs.new_tag }}',
              sha: context.sha
            });
            github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'v' + '${{ steps.increment_version.outputs.new_tag }}',
              message: 'Release v' + '${{ steps.increment_version.outputs.new_tag }}'
            });


  publish:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get the tag from build_and_test job
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)
          echo "new_tag=$(echo $latest_tag | sed 's/^v//')" >> $GITHUB_OUTPUT 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:v${{ steps.get_tag.outputs.new_tag }} 
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max